package Parser;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _bool = 28;
  public static final int CONST = 3;
  public static final int LESSE = 13;
  public static final int GREAT = 14;
  public static final int write = 30;
  public static final int CONTINUE = 37;
  public static final int DOTCOMMA = 18;
  public static final int LESS = 12;
  public static final int LV = 21;
  public static final int AND = 4;
  public static final int real = 25;
  public static final int RV = 22;
  public static final int LP = 19;
  public static final int OR = 5;
  public static final int COMMA = 23;
  public static final int read = 29;
  public static final int DIV = 9;
  public static final int BEGIN = 32;
  public static final int RP = 20;
  public static final int PLUS = 6;
  public static final int MIN = 8;
  public static final int ASSIGN = 11;
  public static final int IF = 34;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int RETURN = 38;
  public static final int error = 1;
  public static final int MUL = 7;
  public static final int MOD = 10;
  public static final int NEQ = 17;
  public static final int BREAK = 36;
  public static final int EQ = 16;
  public static final int in_the_beginning = 24;
  public static final int _while = 31;
  public static final int ELSE = 35;
  public static final int _int = 26;
  public static final int _char = 27;
  public static final int END = 33;
  public static final int GREATE = 15;
  public static final int STRING = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "CONST",
  "AND",
  "OR",
  "PLUS",
  "MUL",
  "MIN",
  "DIV",
  "MOD",
  "ASSIGN",
  "LESS",
  "LESSE",
  "GREAT",
  "GREATE",
  "EQ",
  "NEQ",
  "DOTCOMMA",
  "LP",
  "RP",
  "LV",
  "RV",
  "COMMA",
  "in_the_beginning",
  "real",
  "_int",
  "_char",
  "_bool",
  "read",
  "write",
  "_while",
  "BEGIN",
  "END",
  "IF",
  "ELSE",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "STRING"
  };
}

